=== akansha122/MyWeb/BookXmlSchemaProject/bin/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.zensar.com/books"
	xmlns:zen="http://www.zensar.com/books" elementFormDefault="qualified">
	<element name="book-info">
		<complexType>
			<sequence>
				<element name="book" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="book-id">
								<simpleType>
									<restriction base="int">
										<minInclusive value="1001"></minInclusive>
										<maxInclusive value="9999"></maxInclusive>
										<totalDigits value="4"></totalDigits>
									</restriction>
								</simpleType>
							</element>
							<element name="title">
								<simpleType>
									<restriction base="string">
										<minLength value="3"></minLength>
									</restriction>
								</simpleType>
							</element>
							<element name="author" type="string" maxOccurs="unbounded"/>
							<element name="price" type="float" minOccurs="0"/>
							<element name="publish_date" type="date"/> 
						 </sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== akansha122/MyWeb/BookXmlSchemaProject/bin/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<zen:book-info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zen="http://www.zensar.com/books" xsi:schemaLocation="http://www.zensar.com/books books.xsd ">
   <zen:book>
    <zen:book-id>1001</zen:book-id>
    <zen:title>Java</zen:title>
    <zen:author> Chetan_bhagat</zen:author>
    <zen:publish_date>2001-02-05</zen:publish_date>
   </zen:book>
   
   <zen:book>
    <zen:book-id>1002</zen:book-id>
    <zen:title>MySQL</zen:title>

    <zen:author>Durga_Soft</zen:author>
    <zen:publish_date>1999-10-23</zen:publish_date>
   </zen:book>
 </zen:book-info>
